# Genres of Scientific Text {#genres-sci-text}

::: time
50-90 minutes
:::

Have students share the concept maps they made during Lesson 1. It is recommended that each group present and discuss their concept map with the rest of the class (2-5 minutes). Suggested discussion points include: 

- Are there trends in the types of careers that people chose to map? 
- Do you see any trends for common or unique links associated between similar or different types of concepts? 
- So, what do we think about scientists?  

*Be receptive to different ideas for how students constructed their concept maps, however avoid the 0-0-0-0-0-0- style (i.e., long chain without interlinking), AND the “daisy” with one central word and a single link to a bunch of words in a circle around it (also not thoughtfully interlinked enough).  It will be interesting to note and have students reflect upon the types of preconceived notions that your students have about science & scientists, before they engage in the CREATE-an-APL unit.*  

Next, shift gears. Explain that the students will later apply their concept-mapping skills to clarify their understanding of a scientific paper.  

::: emphasize
Emphasize that an essential skill in both academic and industry-based STEM careers is to be able to read and interpret scientific papers
:::

Without assuming anything about the prior knowledge of your students, pose this question to the class, 

> what is a primary (sourced) scientific paper and how does it differ than other scientific and or non-scientific texts?.

After briefly outlining these different sources of texts, have students pick a topic that they are interested in “googling” and have them locate a few examples of texts that cover this topic, including from 

i. primary literature-based databases such as Pubmed, Web of Science, and  Google Scholar, 
ii. popular press sources such as National Geographic and Scientific American, 
iii. a textbook, and 
iv. social media platforms such as Facebook and Twitter.  

Next, students should skim through text from each genre and note the types of structure and language that each text uses. The goal is not to critically evaluate or judge the findings of these texts, but rather to 

i. compare general format/styles/language of each text, 
ii. if applicable, make observations about the type of research study that was done (i.e., observational versus experimental—this does not need to be formally defined at this point, but students should begin to see differences in the design of different scientific studies) and 
iii. discuss the type of rigor/peer-review accountability that each text must go through prior to publication (a conversation about citations can be used to initiate discussion). 

(see handout # 2 for more details)
