# Science as a career: from business to academia

After completing the APL unit, it is the hope that students will have gained a more authentic view of the process of science, as well as how it is practiced. To help augment reflection on these potential gains,  

> You have seen that Scientists must be skilled at taking a complex, big-picture problem and breaking it down into manageable components that can be analyzed by research.  This requires   But we have also seen that science is not done in isolation, and that previous data is the gold currency for forging new ideas and experimental directions.  We have seen that scientists possess a wide array of skills that range from analytical to nuanced data visualization and communication-based skills, all of which are necessary to actually practicing science. In this context, describe some skills or things that scientists do that were perhaps not a surprise to you after reading the APL. On the flip side, what are some things that you now realize about the process of science or scientists themselves that you may have not previously considered or even were surprised to find out? 

Some points that are important to hit include:

1. Stay updated on the current literature in their field (i.e., what students are currently learning how to interpret—potentially appealing to reading-oriented students)
2. Become an expert technical writers to communicate their ideas (i.e., publish grants, manuscripts, and other communications –potentially attractive to english-oriented students). 
3. Scientists need to apply quantitative reasoning skills to design experiments and interpret data (i.e., math and statistics-oriented students)
4. Scientists must be adept at organizing and visualizing information and data (i.e., cartoon diagrams and models, as well as clear data figures, charts and tables--art-oriented students).
5. Be a content specialist capable of defining and executing experiments using very specific research methods ( i.e., conduct laboratory experiments—potentially appealing to laboratory/hands-on oriented people)
6. Because the work of scientists often lead to new technologies and products sometimes scientists engage in legal and business ventures (i.e., file patents, start their own business—law or business-oriented students). 
The idea here, is that students are made to realize that scientists may be more than what they thought they were during the concept map making exercise—Indeed they wear many different hats, and there is never a dull moment. 

Lesson wrap-up: Life as a researcher-Graduate student seminar 

Graduate student gives a traditional research talk to students about the APL-unit they just completed.

Students should have prepared questions for the graduate student that will be discussed during an open Q and A forum after the seminar is finished.
